#pragma once

#include "NativeGameplayTags.h"

// Tags nativos: disponibles en tiempo de construcción de CDOs (los GEs C++ los
// necesitan en sus constructores, antes de que se garantice la carga del ini).
namespace AmaruTags
{
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Death);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Kill);

	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stealth);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Focus);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rage);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Protected);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Haste);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Slowed);

	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cooldown);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Heal);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Shield);

	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Ultimate);

	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Atoq_Primary);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Atoq_Ability1);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Atoq_Ability2);

	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Pachamama_Primary);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Pachamama_Ability1);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Pachamama_Ability2);

	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Wayra_Primary);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Wayra_Ability1);
	AMARUSHOOTER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Wayra_Ability2);
}
